services:
  user-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.user-service
    env_file:
      - ./apps/user-service/.env.user
    ports:
      - "50051:50051"
    networks:
      - backend

  auth-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth-service
    env_file:
      - ./apps/auth-service/.env.auth
    ports:
      - "50052:50052"
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    env_file:
      - ./apps/gateway/.env.gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - auth-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
