services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user-service
    container_name: user-service
    ports:
      - "50051:50051"
    environment:
      - NODE_ENV=production
      - GRPC_BIND_URL=0.0.0.0:50051
    networks:
      - backend
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - USER_SERVICE_URL=user-service:50051
    depends_on:
      - user-service
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
