services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user-service
    ports:
      - "50051:50051"
    environment:
      - GRPC_BIND_URL=0.0.0.0:50051
    networks:
      - backend

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth-service
    ports:
      - "50052:50052"
    environment:
      - GRPC_BIND_URL=0.0.0.0:50052
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=user-service:50051
      - AUTH_SERVICE_URL=auth-service:50052
    depends_on:
      - user-service
      - auth-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
